name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - run: docker build -t vpiili/gambina .
    - run: echo $@DOCKER_PAT | docker login ghcr.io -u vpiili --password-stdin
    - run: docker push vpiili/gambina:latest
